In [1]:
import pickle
import os
import glob
import numpy as np
import json
from scipy.stats import norm

In [2]:
path = "/home/jenna/sacro_results/results/"

In [3]:
os.listdir(path)

['cf7cf863-929a-4b89-962b-7913869167e4',
 'a90983a1-2329-4019-96e8-949493c3fc24',
 '315ac662-9e95-4dec-80f0-48e244f9f8e1',
 'b71b28f1-7f63-4593-bdb2-9e60dd1ac71e',
 '96c75293-2026-48af-ad99-37281cb9bb3e',
 '436c714b-b588-4894-b68c-1e0f773e5df1',
 '5238ac7b-ad85-488f-b013-9ee4e2064e60',
 'e8d7e0c4-b293-43ce-832f-c37fb8fd3b23',
 'e6a9f8f7-8024-42d5-aad5-ef726d353f3b',
 '26d9e19b-59ed-4bbb-906a-9953b5d2c825',
 'a3347182-4364-43f8-8992-2409b1b66d31',
 'f63b25f4-8df4-4336-8c02-9456eb3c09b0',
 'slinwin_processor.py',
 'e8d3eabc-edd1-414f-9d95-277df742655a',
 'b6701cb1-3a9b-456e-ad73-c6e06eea03ec']

In [4]:
# Now, you need to loop through every video and document the label list and label freq
# Put above code into function
def get_label_list_and_freq(full_path):
#     pred_labels = pickle.load(open(full_path + "/seq_pred.pickle", 'rb'))
    true_labels = pickle.load(open(full_path + "/seq_true.pickle", 'rb'))
    # scan through the true labels to see whether there are early phases repeating in the later stage
    labels_list = []
    labels_freq = []
    for current_label in true_labels:
        #if list is empty or current label is not the same as the previous label, 
        #then append the current label and frequency
        if (not labels_list) or (current_label != labels_list[-1]):
            labels_list.append(current_label)
            labels_freq.append(1)
            continue
        # for the other cases, simply update frequency
        labels_freq[-1] += 1
    return (labels_list, labels_freq)

In [5]:
# Get the list of python files which are no subdirectories
py_files = glob.glob(path+"*.py")
for (i, file) in enumerate(py_files):
    file = file.replace(path, "")
    py_files[i] = file

In [6]:
# Remove the python file(s)
subdir_list = os.listdir(path)
for file in py_files:
    subdir_list.remove(file)
subdir_list

['cf7cf863-929a-4b89-962b-7913869167e4',
 'a90983a1-2329-4019-96e8-949493c3fc24',
 '315ac662-9e95-4dec-80f0-48e244f9f8e1',
 'b71b28f1-7f63-4593-bdb2-9e60dd1ac71e',
 '96c75293-2026-48af-ad99-37281cb9bb3e',
 '436c714b-b588-4894-b68c-1e0f773e5df1',
 '5238ac7b-ad85-488f-b013-9ee4e2064e60',
 'e8d7e0c4-b293-43ce-832f-c37fb8fd3b23',
 'e6a9f8f7-8024-42d5-aad5-ef726d353f3b',
 '26d9e19b-59ed-4bbb-906a-9953b5d2c825',
 'a3347182-4364-43f8-8992-2409b1b66d31',
 'f63b25f4-8df4-4336-8c02-9456eb3c09b0',
 'e8d3eabc-edd1-414f-9d95-277df742655a',
 'b6701cb1-3a9b-456e-ad73-c6e06eea03ec']

In [7]:
# Loop through the subdirectory and extract the label lists and frequencies
data_dict = {}
for subdir in subdir_list:
    full_path = path + subdir
    labels_list, labels_freq = get_label_list_and_freq(full_path)
    # store the list and corresponding frequency into a dictionary
    labels_dict = {}
    labels_dict["label list"] = labels_list
    labels_dict["label freq"] = labels_freq
    # store the label dictionary into the data dictionary under the corresponding subdirectory
    data_dict[subdir] = labels_dict

In [8]:
print(data_dict)

{'cf7cf863-929a-4b89-962b-7913869167e4': {'label list': [1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5], 'label freq': [169, 8, 593, 12, 455, 1, 24, 6, 344, 9, 192]}, 'a90983a1-2329-4019-96e8-949493c3fc24': {'label list': [1, 0, 2, 0, 3, 0, 4, 0, 5], 'label freq': [41, 16, 334, 106, 476, 4, 7, 22, 120]}, '315ac662-9e95-4dec-80f0-48e244f9f8e1': {'label list': [1, 2, 0, 3, 0, 4, 0, 3, 0, 5], 'label freq': [84, 231, 23, 544, 24, 26, 39, 192, 7, 184]}, 'b71b28f1-7f63-4593-bdb2-9e60dd1ac71e': {'label list': [1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5], 'label freq': [47, 3, 846, 1, 394, 3, 23, 10, 143, 2, 109]}, '96c75293-2026-48af-ad99-37281cb9bb3e': {'label list': [2, 1, 2, 0, 3, 0, 4, 0, 3, 0, 5], 'label freq': [146, 101, 254, 17, 550, 1, 73, 14, 190, 15, 266]}, '436c714b-b588-4894-b68c-1e0f773e5df1': {'label list': [1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5], 'label freq': [153, 45, 348, 39, 346, 2, 51, 17, 221, 10, 131]}, '5238ac7b-ad85-488f-b013-9ee4e2064e60': {'label list': [1, 0, 2, 0, 3, 0, 4, 0, 5], 'label freq': [

# Get other prior statistics from ground truth

### Prior Parameters

In [9]:
for vid in data_dict:
    print("{}:".format(vid))
    print("label list:{}\nlabel freq:{}".format(data_dict[vid]["label list"], data_dict[vid]["label freq"]))

cf7cf863-929a-4b89-962b-7913869167e4:
label list:[1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5]
label freq:[169, 8, 593, 12, 455, 1, 24, 6, 344, 9, 192]
a90983a1-2329-4019-96e8-949493c3fc24:
label list:[1, 0, 2, 0, 3, 0, 4, 0, 5]
label freq:[41, 16, 334, 106, 476, 4, 7, 22, 120]
315ac662-9e95-4dec-80f0-48e244f9f8e1:
label list:[1, 2, 0, 3, 0, 4, 0, 3, 0, 5]
label freq:[84, 231, 23, 544, 24, 26, 39, 192, 7, 184]
b71b28f1-7f63-4593-bdb2-9e60dd1ac71e:
label list:[1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5]
label freq:[47, 3, 846, 1, 394, 3, 23, 10, 143, 2, 109]
96c75293-2026-48af-ad99-37281cb9bb3e:
label list:[2, 1, 2, 0, 3, 0, 4, 0, 3, 0, 5]
label freq:[146, 101, 254, 17, 550, 1, 73, 14, 190, 15, 266]
436c714b-b588-4894-b68c-1e0f773e5df1:
label list:[1, 0, 2, 0, 3, 0, 4, 0, 3, 0, 5]
label freq:[153, 45, 348, 39, 346, 2, 51, 17, 221, 10, 131]
5238ac7b-ad85-488f-b013-9ee4e2064e60:
label list:[1, 0, 2, 0, 3, 0, 4, 0, 5]
label freq:[54, 1, 728, 28, 379, 14, 21, 62, 151]
e8d7e0c4-b293-43ce-832f-c37fb8fd3b23:
label l

### Initialisation probability

In [10]:
# Initialisation probability
def getInitProb(data_dict):
    # initialise 
    init_count = np.array([0]*6)
    for vid in data_dict:
        init_phase = data_dict[vid]['label list'][0]
        init_count[init_phase] += 1
    print("Count of initial phases: {}".format(init_count))
    total = np.sum(init_count)
    print("Total:{}".format(total))
    
    init_prob = np.array([0.0]*6)
    for i in range(len(init_prob)):
        init_prob[i] = init_count[i]/total
    print("Initialisation probability vector: {}".format(init_prob))
    return init_prob

In [11]:
init_prob = getInitProb(data_dict)

Count of initial phases: [ 0 11  3  0  0  0]
Total:14
Initialisation probability vector: [0.         0.78571429 0.21428571 0.         0.         0.        ]


### Mean and Standard deviation of percentage length of each phase


In [12]:
# Get phase duration percentage for each video
def getPhasePercByVid(data_dict):
    # dictionary to store all percentage vectors
    phase_perc_mat = np.array([[0,0,0,0,0,0]])
    for vid in data_dict:
        # init a counter for every video
        phase_count = np.array([0]*6)
        # get total frame in the end
        total = 0
        
        for index, freq in enumerate(data_dict[vid]['label freq']):
            # get the corresponding label and add the counts to the label
            phase_count[data_dict[vid]['label list'][index]] += freq
            total += freq
        
        # get the percentage for each phase
        phase_perc = np.array([0.0]*6)
        for i in range(6):
            phase_perc[i] = phase_count[i]/total
            
        # add the vector to the dictionary
        phase_perc_mat = np.append(phase_perc_mat, np.array([phase_perc]), axis=0)
    
    # remove the first array that gives the shape of the numpy array
    return np.delete(phase_perc_mat, 0, axis=0)

In [13]:
phase_perc_mat_by_vid = getPhasePercByVid(data_dict)
print("Phase percentage matrix by video:")
print(phase_perc_mat_by_vid)
print("Shape of matrix:{}".format(phase_perc_mat_by_vid.shape))
print("Total number of videos:{}".format(len(phase_perc_mat_by_vid)))

Phase percentage matrix by video:
[[0.01985659 0.09321566 0.32708218 0.44070601 0.01323773 0.10590182]
 [0.13143872 0.03641208 0.29662522 0.42273535 0.0062167  0.10657194]
 [0.06868538 0.0620384  0.17060561 0.54357459 0.01920236 0.13589365]
 [0.01201771 0.02972802 0.53510436 0.33965844 0.01454775 0.06894371]
 [0.02888752 0.06207744 0.24585126 0.45482483 0.04486785 0.16349109]
 [0.08290536 0.11225238 0.25531915 0.41599413 0.03741746 0.09611152]
 [0.07301808 0.03755216 0.50625869 0.2635605  0.01460362 0.10500695]
 [0.03771429 0.14285714 0.29371429 0.33714286 0.03657143 0.152     ]
 [0.07332564 0.0386836  0.37471132 0.34988453 0.02424942 0.1391455 ]
 [0.0499232  0.05299539 0.25652842 0.47695853 0.00460829 0.15898618]
 [0.05417118 0.00758397 0.14842904 0.54279523 0.01625135 0.23076923]
 [0.03067093 0.12907348 0.28753994 0.46964856 0.01469649 0.06837061]
 [0.08295762 0.0613165  0.4220018  0.42560866 0.00811542 0.        ]
 [0.05393939 0.0830303  0.44909091 0.28545455 0.05636364 0.07212121]]

In [14]:
# Get phase duration percentage for each phase across all videos
# Output is a dictionary indexed by each phase. The value is the length of the key phase across all videos
def getPhasePercByPhase(phase_perc_mat_by_vid):
    return phase_perc_mat_by_vid.T
    

In [15]:
phase_perc_mat_by_phase = getPhasePercByPhase(phase_perc_mat_by_vid)
print(phase_perc_mat_by_phase)

[[0.01985659 0.13143872 0.06868538 0.01201771 0.02888752 0.08290536
  0.07301808 0.03771429 0.07332564 0.0499232  0.05417118 0.03067093
  0.08295762 0.05393939]
 [0.09321566 0.03641208 0.0620384  0.02972802 0.06207744 0.11225238
  0.03755216 0.14285714 0.0386836  0.05299539 0.00758397 0.12907348
  0.0613165  0.0830303 ]
 [0.32708218 0.29662522 0.17060561 0.53510436 0.24585126 0.25531915
  0.50625869 0.29371429 0.37471132 0.25652842 0.14842904 0.28753994
  0.4220018  0.44909091]
 [0.44070601 0.42273535 0.54357459 0.33965844 0.45482483 0.41599413
  0.2635605  0.33714286 0.34988453 0.47695853 0.54279523 0.46964856
  0.42560866 0.28545455]
 [0.01323773 0.0062167  0.01920236 0.01454775 0.04486785 0.03741746
  0.01460362 0.03657143 0.02424942 0.00460829 0.01625135 0.01469649
  0.00811542 0.05636364]
 [0.10590182 0.10657194 0.13589365 0.06894371 0.16349109 0.09611152
  0.10500695 0.152      0.1391455  0.15898618 0.23076923 0.06837061
  0.         0.07212121]]


In [16]:
# Get mean and std from each phase's length distribution
def getMeanAndStd(phase_perc_mat_by_phase):
    norm_params_dict = {}
    for phase, lengths in enumerate(phase_perc_mat_by_phase):
        mu, std = norm.fit(lengths)
        norm_params_dict[phase] = (mu, std)
    return norm_params_dict

In [17]:
norm_params_dict = getMeanAndStd(phase_perc_mat_by_phase)
for k, v in norm_params_dict.items():
    print("Duration percentage of phase {} has mean and std : {}". format(k, v))

Duration percentage of phase 0 has mean and std : (0.05710797112220632, 0.030321443261777936)
Duration percentage of phase 1 has mean and std : (0.06777261004314016, 0.03816546406393554)
Duration percentage of phase 2 has mean and std : (0.3263472992450161, 0.11284218205253618)
Duration percentage of phase 3 has mean and std : (0.4120390546260583, 0.08352923836196571)
Duration percentage of phase 4 has mean and std : (0.022210679714868137, 0.015080408295242551)
Duration percentage of phase 5 has mean and std : (0.11452238524871104, 0.053481343652044204)


### Transition probability matrix without zero

In [18]:
def getTransProbMatWithoutZero(data_dict):
    # The transition matrix here excludes phase zero
    # count transitions from phase i to all phases and devided by total transitions made from phase i
    trans_mat = np.array([[0.0]*5]*5)
    for vid in data_dict:
        label_list = data_dict[vid]["label list"]
        label_freq = data_dict[vid]["label freq"]
        total_trans_label_list = len(label_list)
        prev_phase = 0
        for index, phase in enumerate(label_list):
            # add freq-1 for each phase to the same phase transition
            # at the end of current label, add 1 to the transition 
            if phase == 0:
                continue
            if prev_phase != 0:
                trans_mat[prev_phase-1][phase-1] += 1
            trans_mat[phase-1][phase-1] += label_freq[index] - 1
            prev_phase = phase
#         print("Counting of transitions for {} looks like...".format(vid))
#         print(trans_mat)
    # calculate the probability of transition for each row
    for i in range(len(trans_mat)):
        total = np.sum(trans_mat[i])
        trans_mat[i] = trans_mat[i]/total
        
    print("Final transition probability matrix without phase zero looks like...")
    print(trans_mat)
    return trans_mat

In [19]:
np.set_printoptions(suppress=True, precision=6)
trans_mat_wo_zero = getTransProbMatWithoutZero(data_dict)

Final transition probability matrix without phase zero looks like...
[[0.989426 0.010574 0.       0.       0.      ]
 [0.00046  0.997391 0.002149 0.       0.      ]
 [0.       0.       0.996975 0.001765 0.00126 ]
 [0.       0.       0.024719 0.968539 0.006742]
 [0.       0.       0.       0.       1.      ]]


## Continuous Time Markov Chain : use exponential decay for staying in the current phase